# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# License found in the LICENSE file in the root directory
# of this source tree.
{{- if .Values.enableServiceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "whatsapp-proxy-chart.fullname" . }}-servicemonitor
  labels:
    release: {{ .Values.prometheus.release }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: stats
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      {{- include "whatsapp-proxy-chart.selectorLabels" . | nindent 6 }}
{{- end }}
