name: Docker Image Build for PRs

on:
  pull_request:
    types: [opened, reopened, sychronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: facebook/whatsapp_proxy
        tags: |
          type=raw,value={{date 'YYYYMMDD'}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build PR
      uses: docker/build-push-action@v3
      with:
        context: ./proxy
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        push: false
        tags: |
          ${{ steps.meta.outputs.tags }}
          facebook/whatsapp_proxy:latest
